kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: openjdk:8-jdk
  commands:
  - ./gradlew --no-daemon build
- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: https://git.jcm.re
    files:
      - build/libs/*
      - build/distributions/*
    prerelease: true
