kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: openjdk:8-jdk
  commands:
  - ./gradlew --no-daemon build
- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: https://git.jcm.re
    files:
      - build/libs/*
      - build/distributions/*
  when:
    event:
    - tag
- name: publish_artifact
  image: curlimages/curl
  environment:
    GITEA_TOKEN:
      from_secret: gitea_token
    GITEA_USER:
      from_secret: gitea_user
  commands:
  - curl --user ${GITEA_USER}:${GITEA_TOKEN} --upload-file build/libs/DynamicWallpaper-*-all.jar https://git.jcm.re/api/packages/${DRONE_REPO_OWNER}/generic/${DRONE_REPO_NAME}/${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:8}/Dynam
icWallpaper-all.jar
  when:
    event:
    - push
